### ISSUE TITLE
rss format difference with nitter rss results

### ISSUE THREAD

**Issue by sajiljosephs** [derat/nitter-rss-proxy#10]
rss from nitter:

<title>The Exp 68 crew started the new week investigating astrobiology and keeping up with cargo operations and equipment maintenance. https://go.nasa.gov/3n9KoOA</title>
dc:creator@Space_Station</dc:creator>
The Exp 68 crew started the new week investigating astrobiology and keeping up with cargo operations and equipment maintenance. [go.nasa.gov/3n9KoOA](https://go.nasa.gov/3n9KoOA)

]]>
Mon, 20 Mar 2023 22:02:01 GMT
https://twitter.com/Space_Station/status/1637937566308528128#m
https://twitter.com/Space_Station/status/1637937566308528128#m
rss from nitter-rss-proxy

<title>The Exp 68 crew started the new week investigating astrobiology and keeping up …</title>
https://twitter.com/Space_Station/status/1637937566308528128
<p>The Exp 68 crew started the new week investigating astrobiology and keeping up with cargo operations and equipment maintenance. <a href="https://go.nasa.gov/3n9KoOA&#34;&gt;go.nasa.gov/3n9KoOA&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;img src="https://twitter.com/pic/card_img%2F1637935153325527047%2FzOO6Pgo4%3Fformat%3Djpg%26name%3D800x419&#34; style="max-width:250px;" />
content:encodedThe Exp 68 crew started the new week investigating astrobiology and keeping up with cargo operations and equipment maintenance. [go.nasa.gov/3n9KoOA](https://go.nasa.gov/3n9KoOA)

]]></content:encoded>
@Space_Station
https://twitter.com/Space_Station/status/1637937566308528128
Mon, 20 Mar 2023 22:02:01 +0000
There are many extra characters while rendering the results. I tried with all the 3, "atom", "json", "rss" and its not as same as nitter. Can we have the same results as nitter rss gives ?

**Comment by sajiljosephs** [comment]
This is what visible from nitter rss:
`<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">`
May be the version differs.

**Comment by derat** [comment]
If you change this code:

https://github.com/derat/nitter-rss-proxy/blob/233cf821b868ebdde690d59078d5f499be9623c4/main.go#L177-L180

to this:

```go
w.Write(b)
```

does it do what you want?

If so, I can add a flag to request this behavior.

If this is really what you want, I'm not sure why you're using this proxy instead of calling Nitter directly. If you describe your use case so I can understand what you're trying to do, I may be able to suggest better alternatives.

**Comment by derat** [comment]
No response, so closing.
