### ISSUE TITLE
Support depoly to Railway.

### ISSUE THREAD

**Issue by cxplay** [derat/nitter-rss-proxy#11]
I tried to deploy dockerfile to Railway, But no way to respond successfully anyway. Hope to provide a Railway instance for reference.

**Comment by derat** [comment]
I don't know what Railway is. The Dockerfile in this repo works, as far as I'm aware, so your best bet is probably to ask for help in a Railway support forum.

**Comment by cxplay** [comment]
Thanks for the reply, Railway is a PaaS service that can recognize dockerfile and provide online deployment service. You can find Railway here: https://railway.app.
I've tried looking for the cause, but I can't find an error response in the logs. I have successfully deployed a similar dockerfile project here, but this project was successfully deployed without responding or error logs, so my first step is to ask you for help and then the platform.

**Comment by derat** [comment]
Sorry, beats me. I don't even really use Docker; I just added the Dockerfile here because someone asked for it.

**Comment by cxplay** [comment]
Okay... thank you for your reply. I'll try something else.

**Comment by cxplay** [comment]
Okay... thank you for your reply. I'll try something else.
