### ISSUE TITLE
Support for access control parameters.

### ISSUE THREAD

**Issue by cxplay** [derat/nitter-rss-proxy#12]
I have successfully deployed my nitter-rss-proxy using Dockerfile, the experience is very, very good! 
However, since the service is exposed to the public network, I would like to add access control, such as an access key-based approach similar to [RSSHub](https://docs.rsshub.app/en/install/#configuration-access-control-configuration), to verify authentication parameters when requesting through the proxy.

**Comment by derat** [comment]
I'm glad that the Dockerfile works for you!

This is just a simple proxy, so I'd rather not add (and maintain) support for an access control system on top of it. I'd recommend using an HTTP server like nginx or lighttpd as a reverse proxy and adding access control (e.g. IP-based or HTTP Basic Auth) there.

**Comment by cxplay** [comment]
OK! Thank you for your reply.
