### ISSUE TITLE
only first 20 tweets

### ISSUE THREAD

**Issue by sajiljosephs** [derat/nitter-rss-proxy#9]
I could get only first 20 tweets. Is there an option to set a date range to get the tweets?

**Comment by derat** [comment]
Like I said in #6, this is just a proxy, so it will return however many items it gets from the Nitter instance. Please read the Nitter documentation and issues. Here are some issues I saw that seem relevant:
* https://github.com/zedeus/nitter/issues/228
* https://github.com/zedeus/nitter/issues/561
* https://github.com/zedeus/nitter/issues/655

If there are headers or query parameters that the proxy needs to pass through via the request to Nitter in order to get more items (or customize the request in any other way), I'll be happy to add support for them if you tell me the specifics.

**Comment by sajiljosephs** [comment]
this has the cursor count set to 20 and thats why its just 20 tweets. Can we have this increased ?
https://github.com/zedeus/nitter/blob/687447cea43089e0550ed47656535e11ba8f69f8/src/apiutils.nim#L14

**Comment by sajiljosephs** [comment]
Eg: https://nitter.net/Reuters/rss >  Gives 1st 20 tweets
Min-id for this URL is : HBaGgNPh8K+Xui0AAA==
We can get next 20 tweets with the URL
https://nitter.net/Reuters/rss?max_position=HBaGgNPh8K+Xui0AAA==

Similarly nitter-rss-proxy doesnt change the results by adding min-id to the nitter-rss-proxy url
http://nitter-rss-proxy/Reuters?max_position=HBaGgNPh8K+Xui0AAA== >> Gives 1st 20 tweets only
http://nitter-rss-proxy/Reuters/rss?max_position=HBaGgNPh8K+Xui0AAA== >> Gives the 1st 20 tweets for the user rss

Can we add this to nitter-rss-proxy. Eg: When we access 
http://nitter-rss-proxy/Reuters/rss?max_position=HBaGgNPh8K+Xui0AAA== or 
http://nitter-rss-proxy/Reuters?max_position=HBaGgNPh8K+Xui0AAA==
 it should get the results from https://nitter.net/Reuters/rss?max_position=HBaGgNPh8K+Xui0AAA==

**Comment by derat** [comment]
Thanks for the details. The proxy now copies `Min-Id` headers to responses and includes `max_position` query parameters in requests.

**Comment by sajiljosephs** [comment]
rss from nitter:
<item>
      <title>The Exp 68 crew started the new week investigating astrobiology and keeping up with cargo operations and equipment maintenance. https://go.nasa.gov/3n9KoOA</title>
      <dc:creator>@Space_Station</dc:creator>
      <description><![CDATA[<p>The Exp 68 crew started the new week investigating astrobiology and keeping up with cargo operations and equipment maintenance. <a href="https://go.nasa.gov/3n9KoOA">go.nasa.gov/3n9KoOA</a></p>
<img src="https://twitter.com/pic/card_img%2F1637935153325527047%2FzOO6Pgo4%3Fformat%3Djpg%26name%3D800x419" style="max-width:250px;" />]]></description>
      <pubDate>Mon, 20 Mar 2023 22:02:01 GMT</pubDate>
      <guid>https://twitter.com/Space_Station/status/1637937566308528128#m</guid>
      <link>https://twitter.com/Space_Station/status/1637937566308528128#m</link>
    </item>

rss from nitter-rss-proxy
    <item>
      <title>The Exp 68 crew started the new week investigating astrobiology and keeping up …</title>
      <link>https://twitter.com/Space_Station/status/1637937566308528128</link>
      <description>&lt;p&gt;The Exp 68 crew started the new week investigating astrobiology and keeping up with cargo operations and equipment maintenance. &lt;a href=&#34;https://go.nasa.gov/3n9KoOA&#34;&gt;go.nasa.gov/3n9KoOA&lt;/a&gt;&lt;/p&gt;&lt;br&gt;&lt;img src=&#34;https://twitter.com/pic/card_img%2F1637935153325527047%2FzOO6Pgo4%3Fformat%3Djpg%26name%3D800x419&#34; style=&#34;max-width:250px;&#34; /&gt;</description>
      <content:encoded><![CDATA[<p>The Exp 68 crew started the new week investigating astrobiology and keeping up with cargo operations and equipment maintenance. <a href="https://go.nasa.gov/3n9KoOA">go.nasa.gov/3n9KoOA</a></p><br><img src="https://twitter.com/pic/card_img%2F1637935153325527047%2FzOO6Pgo4%3Fformat%3Djpg%26name%3D800x419" style="max-width:250px;" />]]></content:encoded>
      <author>@Space_Station</author>
      <guid>https://twitter.com/Space_Station/status/1637937566308528128</guid>
      <pubDate>Mon, 20 Mar 2023 22:02:01 +0000</pubDate>
    </item>


There are many extra characters while rendering the results. I tried with all the 3, "atom", "json", "rss" and its not as same as nitter. Can we have the same results as nitter rss gives ?

**Comment by derat** [comment]
> Can we have the same results as nitter rss gives ?

Please request this in a new issue.
